# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= libpipeline
ARCHIVE		= libpipeline-1.5.0.tar.gz
URL		= http://download.savannah.gnu.org/releases/libpipeline
CHECKSUM	= b7437a5020190cfa84f09c412db38902
SOURCE_DIR	= libpipeline-1.5.0

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
