# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= make
ARCHIVE		= make-4.2.1.tar.bz2
URL		= http://ftp.gnu.org/gnu/make
CHECKSUM	= 15b012617e7c44c0ed482721629577ac
SOURCE_DIR	= make-4.2.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
