# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= kbd
ARCHIVE		= kbd-2.0.4.tar.xz
URL		= https://www.kernel.org/pub/linux/utils/kbd
CHECKSUM	= c1635a5a83b63aca7f97a3eab39ebaa6
SOURCE_DIR	= kbd-2.0.4

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
