# $FENRIR: pkg/kbd/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= kbd
ARCHIVE		= kbd-2.0.4.tar.xz
URL		= https://www.kernel.org/pub/linux/utils/kbd
CHECKSUM	= c1635a5a83b63aca7f97a3eab39ebaa6
SOURCE_DIR	= kbd-2.0.4

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
