# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= dejagnu
ARCHIVE		= dejagnu-1.6.1.tar.gz
URL		= http://ftp.gnu.org/gnu/dejagnu
CHECKSUM	= 2ac8405a4c7ca8611d004fe852966c6f
SOURCE_DIR	= dejagnu-1.6.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
