# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= expat
ARCHIVE		= expat-2.2.6.tar.bz2
URL		= https://prdownloads.sourceforge.net/expat
CHECKSUM	= ca047ae951b40020ac831c28859161b2
SOURCE_DIR	= expat-2.2.6

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
