# $FENRIR: pkg/expat/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= expat
ARCHIVE		= expat-2.2.6.tar.bz2
URL		= https://prdownloads.sourceforge.net/expat
CHECKSUM	= ca047ae951b40020ac831c28859161b2
SOURCE_DIR	= expat-2.2.6

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
