# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= python
ARCHIVE		= Python-3.7.0.tar.xz
URL		= https://www.python.org/ftp/python/3.7.0
CHECKSUM	= eb8c2a6b1447d50813c02714af4681f3
SOURCE_DIR	= Python-3.7.0

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
