# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= bzip2
ARCHIVE		= bzip2-1.0.6.tar.gz
URL		= http://anduin.linuxfromscratch.org/LFS
CHECKSUM	= 00b516f4704d4a7cb50a1d97e6e8e15b
SOURCE_DIR	= bzip2-1.0.6

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
