# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= gmp
ARCHIVE		= gmp-6.1.2.tar.xz
URL		= http://ftp.gnu.org/gnu/gmp
CHECKSUM	= f58fa8001d60c4c77595fbbb62b63c1d
SOURCE_DIR	= gmp-6.1.2

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
