# $FENRIR: pkg/mpfr/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= mpfr
ARCHIVE		= mpfr-4.0.1.tar.xz
URL		= http://www.mpfr.org/mpfr-4.0.1
CHECKSUM	= b8dd19bd9bb1ec8831a6a582a7308073
SOURCE_DIR	= mpfr-4.0.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
