# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= gcc
ARCHIVE		= gcc-8.2.0.tar.xz
URL		= http://ftp.gnu.org/gnu/gcc/gcc-8.2.0
CHECKSUM	= 4ab282f414676496483b3e1793d07862
SOURCE_DIR	= gcc-8.2.0

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
