# $FENRIR: pkg/openssl/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= openssl
ARCHIVE		= openssl-1.1.0i.tar.gz
URL		= https://openssl.org/source
CHECKSUM	= 9495126aafd2659d357ea66a969c3fe1
SOURCE_DIR	= openssl-1.1.0i

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
