# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= perl
ARCHIVE		= perl-5.28.0.tar.xz
URL		= https://www.cpan.org/src/5.0
CHECKSUM	= f3245183c0a08f65e94a3333995af08e
SOURCE_DIR	= perl-5.28.0

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
