# $FENRIR: pkg/less/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= less
ARCHIVE		= less-530.tar.gz
URL		= http://www.greenwoodsoftware.com/less
CHECKSUM	= 6a39bccf420c946b0fd7ffc64961315b
SOURCE_DIR	= less-530

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
