# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= less
ARCHIVE		= less-530.tar.gz
URL		= http://www.greenwoodsoftware.com/less
CHECKSUM	= 6a39bccf420c946b0fd7ffc64961315b
SOURCE_DIR	= less-530

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
