# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= inetutils
ARCHIVE		= inetutils-1.9.4.tar.xz
URL		= http://ftp.gnu.org/gnu/inetutils
CHECKSUM	= 87fef1fa3f603aef11c41dcc097af75e
SOURCE_DIR	= inetutils-1.9.4

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
