# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= flex
ARCHIVE		= flex-2.6.4.tar.gz
URL		= https://github.com/westes/flex/releases/download/v2.6.4
CHECKSUM	= 2882e3179748cc9f9c23ec593d6adc8d
SOURCE_DIR	= flex-2.6.4

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
