# $FENRIR: pkg/flex/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= flex
ARCHIVE		= flex-2.6.4.tar.gz
URL		= https://github.com/westes/flex/releases/download/v2.6.4
CHECKSUM	= 2882e3179748cc9f9c23ec593d6adc8d
SOURCE_DIR	= flex-2.6.4

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
