# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= libtool
ARCHIVE		= libtool-2.4.6.tar.xz
URL		= http://ftp.gnu.org/gnu/libtool
CHECKSUM	= 1bfb9b923f2c1339b4d2ce1807064aa5
SOURCE_DIR	= libtool-2.4.6

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
