# $FENRIR: pkg/libtool/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= libtool
ARCHIVE		= libtool-2.4.6.tar.xz
URL		= http://ftp.gnu.org/gnu/libtool
CHECKSUM	= 1bfb9b923f2c1339b4d2ce1807064aa5
SOURCE_DIR	= libtool-2.4.6

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
