# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= eudev
ARCHIVE		= eudev-3.2.5.tar.gz
URL		= https://dev.gentoo.org/~blueness/eudev
CHECKSUM	= 6ca08c0e14380f87df8e8aceac123671
SOURCE_DIR	= eudev-3.2.5

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
