# $FENRIR: pkg/eudev/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= eudev
ARCHIVE		= eudev-3.2.5.tar.gz
URL		= https://dev.gentoo.org/~blueness/eudev
CHECKSUM	= 6ca08c0e14380f87df8e8aceac123671
SOURCE_DIR	= eudev-3.2.5

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
