# $FENRIR: pkg/systemd-man-pages/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= systemd-man-pages
ARCHIVE		= systemd-man-pages-239.tar.xz
URL		= http://anduin.linuxfromscratch.org/LFS
CHECKSUM	= b3be99a8fff33c773f034151b16eb1b8
SOURCE_DIR	= systemd-man-pages-239

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
