# $COBRA$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= autoconf
ARCHIVE		= autoconf-2.69.tar.xz
URL		= http://ftp.gnu.org/gnu/autoconf
CHECKSUM	= 50f97f4159805e374639a73e2636f22e
SOURCE_DIR	= autoconf-2.69

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
