# $FENRIR: pkg/autoconf/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= autoconf
ARCHIVE		= autoconf-2.69.tar.xz
URL		= http://ftp.gnu.org/gnu/autoconf
CHECKSUM	= 50f97f4159805e374639a73e2636f22e
SOURCE_DIR	= autoconf-2.69

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
