# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= pkg-config
ARCHIVE		= pkg-config-0.29.2.tar.gz
URL		= https://pkg-config.freedesktop.org/releases
CHECKSUM	= f6e931e319531b736fadc017f470e68a
SOURCE_DIR	= pkg-config-0.29.2

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
