# $FENRIR: pkg/attr/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= attr
ARCHIVE		= attr-2.4.48.tar.gz
URL		= http://download.savannah.gnu.org/releases/attr
CHECKSUM	= bc1e5cb5c96d99b24886f1f527d3bb3d
SOURCE_DIR	= attr-2.4.48

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
