# $FENRIR: pkg/automake/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= automake
ARCHIVE		= automake-1.16.1.tar.xz
URL		= http://ftp.gnu.org/gnu/automake
CHECKSUM	= 53f38e7591fa57c3d2cee682be668e5b
SOURCE_DIR	= automake-1.16.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
