# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= man-db
ARCHIVE		= man-db-2.8.4.tar.xz
URL		= http://download.savannah.gnu.org/releases/man-db
CHECKSUM	= ab41db551f500e4a595b11203b86c67a
SOURCE_DIR	= man-db-2.8.4

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
