# $FENRIR: pkg/man-db/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= man-db
ARCHIVE		= man-db-2.8.4.tar.xz
URL		= http://download.savannah.gnu.org/releases/man-db
CHECKSUM	= ab41db551f500e4a595b11203b86c67a
SOURCE_DIR	= man-db-2.8.4

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
