# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= python-docs
ARCHIVE		= python-3.7.0-docs-html.tar.bz2
URL		= https://docs.python.org/ftp/python/doc/3.7.0
CHECKSUM	= c4637cf2a9a6ebb8c5e9dc8ff13fb4cb
SOURCE_DIR	= python-3.7.0-docs-html

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
