# $FENRIR: pkg/python-docs/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= python-docs
ARCHIVE		= python-3.7.0-docs-html.tar.bz2
URL		= https://docs.python.org/ftp/python/doc/3.7.0
CHECKSUM	= c4637cf2a9a6ebb8c5e9dc8ff13fb4cb
SOURCE_DIR	= python-3.7.0-docs-html

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
