# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= texinfo
ARCHIVE		= texinfo-6.5.tar.xz
URL		= http://ftp.gnu.org/gnu/texinfo
CHECKSUM	= 3715197e62e0e07f85860b3d7aab55ed
SOURCE_DIR	= texinfo-6.5

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
