# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= grub
ARCHIVE		= grub-2.02.tar.xz
URL		= https://ftp.gnu.org/gnu/grub
CHECKSUM	= 8a4a2a95aac551fb0fba860ceabfa1d3
SOURCE_DIR	= grub-2.02

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
