# $FENRIR: pkg/gperf/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= gperf
ARCHIVE		= gperf-3.1.tar.gz
URL		= http://ftp.gnu.org/gnu/gperf
CHECKSUM	= 9e251c0a618ad0824b51117d5d9db87e
SOURCE_DIR	= gperf-3.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
