# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= glibc
ARCHIVE		= glibc-2.28.tar.xz
URL		= http://ftp.gnu.org/gnu/glibc
CHECKSUM	= c81d2388896379997bc359d4f2084239
SOURCE_DIR	= glibc-2.28

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
