# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= zlib
ARCHIVE		= zlib-1.2.11.tar.xz
URL		= https://zlib.net
CHECKSUM	= 85adef240c5f370b308da8c938951a68
SOURCE_DIR	= zlib-1.2.11

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
