# $COBRA$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= iproute2
ARCHIVE		= iproute2-4.18.0.tar.xz
URL		= https://www.kernel.org/pub/linux/utils/net/iproute2
CHECKSUM	= 8b8680e91390c57cab788fbf8e929479
SOURCE_DIR	= iproute2-4.18.0

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
