# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= libffi
ARCHIVE		= libffi-3.2.1.tar.gz
URL		= ftp://sourceware.org/pub/libffi
CHECKSUM	= 83b89587607e3eb65c70d361f13bab43
SOURCE_DIR	= libffi-3.2.1

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
