# $FENRIR: pkg/libffi/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= libffi
ARCHIVE		= libffi-3.2.1.tar.gz
URL		= ftp://sourceware.org/pub/libffi
CHECKSUM	= 83b89587607e3eb65c70d361f13bab43
SOURCE_DIR	= libffi-3.2.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
