# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= binutils
ARCHIVE		= binutils-2.31.1.tar.xz
URL		= http://ftp.gnu.org/gnu/binutils
CHECKSUM	= 5b7c9d4ce96f507d95c1b9a255e52418
SOURCE_DIR	= binutils-2.31.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
