# $FENRIR: pkg/elfutils/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= elfutils
ARCHIVE		= elfutils-0.173.tar.bz2
URL		= https://sourceware.org/ftp/elfutils/0.173
CHECKSUM	= 35decb1ebfb90d565e4c411bee4185cc
SOURCE_DIR	= elfutils-0.173

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
