# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= elfutils
ARCHIVE		= elfutils-0.173.tar.bz2
URL		= https://sourceware.org/ftp/elfutils/0.173
CHECKSUM	= 35decb1ebfb90d565e4c411bee4185cc
SOURCE_DIR	= elfutils-0.173

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
