# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= gdbm
ARCHIVE		= gdbm-1.17.tar.gz
URL		= http://ftp.gnu.org/gnu/gdbm
CHECKSUM	= f20ce117abc6f302ecf62c34d41c1ecf
SOURCE_DIR	= gdbm-1.17

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
