# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= grep
ARCHIVE		= grep-3.1.tar.xz
URL		= http://ftp.gnu.org/gnu/grep
CHECKSUM	= feca7b3e7c7f4aab2b42ecbfc513b070
SOURCE_DIR	= grep-3.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
