# $FENRIR: pkg/perl-XML-Parser/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= perl-XML-Parser
ARCHIVE		= XML-Parser-2.44.tar.gz
URL		= https://cpan.metacpan.org/authors/id/T/TO/TODDR
CHECKSUM	= af4813fe3952362451201ced6fbce379
SOURCE_DIR	= XML-Parser-2.44

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
