# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= vim
ARCHIVE		= vim-8.1.tar.bz2
URL		= ftp://ftp.vim.org/pub/vim/unix
CHECKSUM	= 1739a1df312305155285f0cfa6118294
SOURCE_DIR	= vim-8.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
