# $FENRIR: pkg/man-pages/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= man-pages
ARCHIVE		= man-pages-4.16.tar.xz
URL		= https://www.kernel.org/pub/linux/docs/man-pages
CHECKSUM	= ad9f1ff81276fe8d90d077484d6d4b5e
SOURCE_DIR	= man-pages-4.16

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
