# $FENRIR: pkg/kmod/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= kmod
ARCHIVE		= kmod-25.tar.xz
URL		= https://www.kernel.org/pub/linux/utils/kernel/kmod
CHECKSUM	= 34f325cab568f842fdde4f8b2182f220
SOURCE_DIR	= kmod-25

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
