# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= kmod
ARCHIVE		= kmod-25.tar.xz
URL		= https://www.kernel.org/pub/linux/utils/kernel/kmod
CHECKSUM	= 34f325cab568f842fdde4f8b2182f220
SOURCE_DIR	= kmod-25

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
