# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= util-linux
ARCHIVE		= util-linux-2.32.1.tar.xz
URL		= https://www.kernel.org/pub/linux/utils/util-linux/v2.32
CHECKSUM	= 9e5b1b8c1dc99455bdb6b462cf9436d9
SOURCE_DIR	= util-linux-2.32.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
