# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= curl
ARCHIVE		= curl-7.63.0.tar.gz
URL		= https://curl.haxx.se/download
CHECKSUM	= 6121427a7199cd6094fc48c9e31e8992
SOURCE_DIR	= curl-7.63.0

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract
	false

test:
	false

install:
	false

.PHONY: default build test install
