# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= bc
ARCHIVE		= bc-1.07.1.tar.gz
URL		= http://ftp.gnu.org/gnu/bc
CHECKSUM	= cda93857418655ea43590736fc3ca9fc
SOURCE_DIR	= bc-1.07.1

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
