# $FENRIR: pkg/tzdata/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= tzdata
ARCHIVE		= tzdata2018e.tar.gz
URL		= https://www.iana.org/time-zones/repository/releases
CHECKSUM	= 97d654f4d7253173b3eeb76a836dd65e
SOURCE_DIR	=

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
