# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= tzdata
ARCHIVE		= tzdata2018e.tar.gz
URL		= https://www.iana.org/time-zones/repository/releases
CHECKSUM	= 97d654f4d7253173b3eeb76a836dd65e
SOURCE_DIR	=

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
