# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= procps-ng
ARCHIVE		= procps-ng-3.3.15.tar.xz
URL		= https://sourceforge.net/projects/procps-ng/files/Production
CHECKSUM	= 2b0717a7cb474b3d6dfdeedfbad2eccc
SOURCE_DIR	= procps-ng-3.3.15

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
