# $FENRIR: pkg/procps-ng/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= procps-ng
ARCHIVE		= procps-ng-3.3.15.tar.xz
URL		= https://sourceforge.net/projects/procps-ng/files/Production
CHECKSUM	= 2b0717a7cb474b3d6dfdeedfbad2eccc
SOURCE_DIR	= procps-ng-3.3.15

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
