# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= gettext
ARCHIVE		= gettext-0.19.8.1.tar.xz
URL		= http://ftp.gnu.org/gnu/gettext
CHECKSUM	= df3f5690eaa30fd228537b00cb7b7590
SOURCE_DIR	= gettext-0.19.8.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
