# $FENRIR: pkg/mpc/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= mpc
ARCHIVE		= mpc-1.1.0.tar.gz
URL		= https://ftp.gnu.org/gnu/mpc
CHECKSUM	= 4125404e41e482ec68282a2e687f6c73
SOURCE_DIR	= mpc-1.1.0

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
