# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= mpc
ARCHIVE		= mpc-1.1.0.tar.gz
URL		= https://ftp.gnu.org/gnu/mpc
CHECKSUM	= 4125404e41e482ec68282a2e687f6c73
SOURCE_DIR	= mpc-1.1.0

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
