# $FENRIR: pkg/meson/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= meson
ARCHIVE		= meson-0.47.1.tar.gz
URL		= https://github.com/mesonbuild/meson/releases/download/0.47.1
CHECKSUM	= 5ed95fd4e9c7634f7cf3482d352804e7
SOURCE_DIR	= meson-0.47.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
