# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= meson
ARCHIVE		= meson-0.47.1.tar.gz
URL		= https://github.com/mesonbuild/meson/releases/download/0.47.1
CHECKSUM	= 5ed95fd4e9c7634f7cf3482d352804e7
SOURCE_DIR	= meson-0.47.1

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
