# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= acl
ARCHIVE		= acl-2.2.53.tar.gz
URL		= http://download.savannah.gnu.org/releases/acl
CHECKSUM	= 007aabf1dbb550bcddde52a244cd1070
SOURCE_DIR	= acl-2.2.53

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
