# $FENRIR: pkg/acl/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= acl
ARCHIVE		= acl-2.2.53.tar.gz
URL		= http://download.savannah.gnu.org/releases/acl
CHECKSUM	= 007aabf1dbb550bcddde52a244cd1070
SOURCE_DIR	= acl-2.2.53

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
