# $FENRIR$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= iana-etc
ARCHIVE		= iana-etc-2.30.tar.bz2
URL		= http://anduin.linuxfromscratch.org/LFS
CHECKSUM	= 3ba3afb1d1b261383d247f46cb135ee8
SOURCE_DIR	= iana-etc-2.30

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
