# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= gzip
ARCHIVE		= gzip-1.9.tar.xz
URL		= http://ftp.gnu.org/gnu/gzip
CHECKSUM	= 9492c6ccb2239ff679a5475a7bb543ed
SOURCE_DIR	= gzip-1.9

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
