# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= expect
ARCHIVE		= expect5.45.4.tar.gz
URL		= https://prdownloads.sourceforge.net/expect
CHECKSUM	= 00fce8de158422f5ccd2666512329bd2
SOURCE_DIR	= expect5.45.4

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
