# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= bash
ARCHIVE		= bash-4.4.18.tar.gz
URL		= http://ftp.gnu.org/gnu/bash
CHECKSUM	= 518e2c187cc11a17040f0915dddce54e
SOURCE_DIR	= bash-4.4.18

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
