# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= shadow
ARCHIVE		= shadow-4.6.tar.xz
URL		= https://github.com/shadow-maint/shadow/releases/download/4.6
CHECKSUM	= b491fecbf1232632c32ff8f1437fd60e
SOURCE_DIR	= shadow-4.6

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
