# $FENRIR: pkg/dbus/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= dbus
ARCHIVE		= dbus-1.12.10.tar.gz
URL		= https://dbus.freedesktop.org/releases/dbus
CHECKSUM	= c3e12b4206e2a7da39d7cc42567790ef
SOURCE_DIR	= dbus-1.12.10

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
