# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= dbus
ARCHIVE		= dbus-1.12.10.tar.gz
URL		= https://dbus.freedesktop.org/releases/dbus
CHECKSUM	= c3e12b4206e2a7da39d7cc42567790ef
SOURCE_DIR	= dbus-1.12.10

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
