# $FENRIR: pkg/systemd/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= systemd
ARCHIVE		= systemd-239.tar.gz
URL		= https://github.com/systemd/systemd/archive/v239
CHECKSUM	= 6137e3f50390391cf34521d071a1a078
SOURCE_DIR	= systemd-239

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
