# $FENRIR: pkg/check/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= check
ARCHIVE		= check-0.12.0.tar.gz
URL		= https://github.com/libcheck/check/releases/download/0.12.0
CHECKSUM	= 31b17c6075820a434119592941186f70
SOURCE_DIR	= check-0.12.0

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
