# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= check
ARCHIVE		= check-0.12.0.tar.gz
URL		= https://github.com/libcheck/check/releases/download/0.12.0
CHECKSUM	= 31b17c6075820a434119592941186f70
SOURCE_DIR	= check-0.12.0

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
