# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= findutils
ARCHIVE		= findutils-4.6.0.tar.gz
URL		= http://ftp.gnu.org/gnu/findutils
CHECKSUM	= 9936aa8009438ce185bea2694a997fc1
SOURCE_DIR	= findutils-4.6.0

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
