# $FENRIR: pkg/intltool/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= intltool
ARCHIVE		= intltool-0.51.0.tar.gz
URL		= https://launchpad.net/intltool/trunk/0.51.0/+download
CHECKSUM	= 12e517cac2b57a0121cda351570f1e63
SOURCE_DIR	= intltool-0.51.0

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
