# $COBRA$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= psmisc
ARCHIVE		= psmisc-23.1.tar.xz
URL		= https://sourceforge.net/projects/psmisc/files/psmisc
CHECKSUM	= bbba1f701c02fb50d59540d1ff90d8d1
SOURCE_DIR	= psmisc-23.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
