# $FENRIR: pkg/psmisc/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= psmisc
ARCHIVE		= psmisc-23.1.tar.xz
URL		= https://sourceforge.net/projects/psmisc/files/psmisc
CHECKSUM	= bbba1f701c02fb50d59540d1ff90d8d1
SOURCE_DIR	= psmisc-23.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
