# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= ncurses
ARCHIVE		= ncurses-6.1.tar.gz
URL		= http://ftp.gnu.org/gnu/ncurses
CHECKSUM	= 98c889aaf8d23910d2b92d65be2e737a
SOURCE_DIR	= ncurses-6.1

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
