# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= readline
ARCHIVE		= readline-7.0.tar.gz
URL		= http://ftp.gnu.org/gnu/readline
CHECKSUM	= 205b03a87fc83dab653b628c59b9fc91
SOURCE_DIR	= readline-7.0

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
