# $FENRIR: pkg/ninja/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= ninja
ARCHIVE		= ninja-1.8.2.tar.gz
URL		= https://github.com/ninja-build/ninja/archive/v1.8.2
CHECKSUM	= 5fdb04461cc7f5d02536b3bfc0300166
SOURCE_DIR	= ninja-1.8.2

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
