# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= ninja
ARCHIVE		= ninja-1.8.2.tar.gz
URL		= https://github.com/ninja-build/ninja/archive/v1.8.2
CHECKSUM	= 5fdb04461cc7f5d02536b3bfc0300166
SOURCE_DIR	= ninja-1.8.2

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
