# $FENRIR$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= libcap
ARCHIVE		= libcap-2.25.tar.xz
URL		= https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2
CHECKSUM	= 6666b839e5d46c2ad33fc8aa2ceb5f77
SOURCE_DIR	= libcap-2.25

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
