# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= m4
ARCHIVE		= m4-1.4.18.tar.xz
URL		= http://ftp.gnu.org/gnu/m4
CHECKSUM	= 730bb15d96fffe47e148d1e09235af82
SOURCE_DIR	= m4-1.4.18

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
