# $FENRIR: pkg/sysklogd/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= sysklogd
ARCHIVE		= sysklogd-1.5.1.tar.gz
URL		= http://www.infodrom.org/projects/sysklogd/download
CHECKSUM	= c70599ab0d037fde724f7210c2c8d7f8
SOURCE_DIR	= sysklogd-1.5.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
