# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= sysklogd
ARCHIVE		= sysklogd-1.5.1.tar.gz
URL		= http://www.infodrom.org/projects/sysklogd/download
CHECKSUM	= c70599ab0d037fde724f7210c2c8d7f8
SOURCE_DIR	= sysklogd-1.5.1

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
