# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= groff
ARCHIVE		= groff-1.22.3.tar.gz
URL		= http://ftp.gnu.org/gnu/groff
CHECKSUM	= cc825fa64bc7306a885f2fb2268d3ec5
SOURCE_DIR	= groff-1.22.3

default: build

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
