# $FENRIR: pkg/e2fsprogs/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= e2fsprogs
ARCHIVE		= e2fsprogs-1.44.3.tar.gz
URL		= https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.44.3
CHECKSUM	= 6bd765f3cf8f15740cdf81e71e88f2a4
SOURCE_DIR	= e2fsprogs-1.44.3

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
