# $FENRIR$
#
# Copyright © 2019, Colvin Wellborn All rights reserved.

PACKAGE		= udev-lfs
ARCHIVE		= udev-lfs-20171102.tar.bz2
URL		= http://anduin.linuxfromscratch.org/LFS
CHECKSUM	= d92afb0c6e8e616792068ee4737b0d24
SOURCE_DIR	= udev-lfs-20171102

default: build install clean

include $(CURDIR)/../../mk/pkg.mk

build: chroot-check fetch extract

test:

install:

.PHONY: default build test install
