# $FENRIR: pkg/udev-lfs/Makefile 8b800ad0c3c6da18caa0053206ed595631f65d1d 2019-01-05T19:35:21-05:00 colvin $
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= udev-lfs
ARCHIVE		= udev-lfs-20171102.tar.bz2
URL		= http://anduin.linuxfromscratch.org/LFS
CHECKSUM	= d92afb0c6e8e616792068ee4737b0d24
SOURCE_DIR	= udev-lfs-20171102

default: build

include $(CURDIR)/../../mk/pkg.mk

build: fetch extract

test:

install:

.PHONY: default build test install
