# $CCL$
#
# Copyright (c) 2019, Colvin Wellborn All rights reserved.

PACKAGE		= tcl
ARCHIVE		= tcl8.6.8-src.tar.gz
URL		= https://downloads.sourceforge.net/tcl
CHECKSUM	= 81656d3367af032e0ae6157eff134f89
SOURCE_DIR	= tcl8.6.8

default: build


include $(CURDIR)/../../mk/pkg.mk


build: fetch extract


test:


install:


.PHONY: default build test install
